Disable motd scripts (#29)

diff --git a/install b/install
--- a/install
+++ b/install
@@ -234,6 +234,15 @@ service supervisor restart >> $LOG_FILE 2>&1
 decho "Disabling swap file..."
 swapoff /swapfile >> $LOG_FILE 2>&1
 
+# disable exitting on error in case DO changes motd scripts
+set +e
+chmod -x /etc/update-motd.d/*-release-upgrade     
+chmod -x /etc/update-motd.d/*-updates-available
+chmod -x /etc/update-motd.d/*-reboot-required
+chmod -x /etc/update-motd.d/*-help-text
+chmod -x /etc/update-motd.d/*-cloudguest
+set -e
+
 echo
 decho "Done! Now it's time to configure Lamassu stack."
 echo
