chore: improve lock error message

diff --git a/upgrade-ls b/upgrade-ls
--- a/upgrade-ls
+++ b/upgrade-ls
@@ -37,7 +37,8 @@ fi
 # Use a lock file so failed scripts cannot be imediately retried
 # If not the backup created on this script would be replaced
 if ! mkdir /var/lock/lamassu-update; then
-  echo "Script is locked because of a failure." >&2
+  echo "It seems the script is already running. Aborting." >&2
+  trap "" EXIT # Don't remove another script's lock
   exit 1
 fi
 
