fix: run EE upgrade only on EE, remove node update

diff --git a/upgrade b/upgrade
--- a/upgrade
+++ b/upgrade
@@ -5,6 +5,8 @@ export LOG_FILE=/tmp/update.$(date +"%Y%m%d").log
 export NPM_BIN=$(npm -g bin)
 
 SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
+SERVER_RELEASE=$(node -p -e "require('$(npm root -g)/lamassu-server/package.json').version")
+REQUIRED_RELEASE=7.5.0
 
 rm -f ${LOG_FILE}
 
@@ -28,6 +30,13 @@ if [ "$(whoami)" != "root" ]; then
   exit 3
 fi
 
+if [ $(printf "%s\n" "$SERVER_RELEASE" "$REQUIRED_RELEASE" | sort -V -r | head -1) = "$REQUIRED_RELEASE" ] ; then
+  echo "This upgrade script is meant to be run on existing v7.5 installations." >&2
+  echo "Please contact support for details on upgrading to v7.5." >&2
+  echo
+  exit 1
+fi
+
 # Use a lock file so failed scripts cannot be imediately retried
 # If not the backup created on this script would be replaced
 if ! mkdir /var/lock/lamassu-update; then
@@ -47,12 +56,6 @@ if [ -d "/usr/lib/node_modules/lamassu-server" ]; then
     decho "renaming old lamassu-server instance to ${BKP_NAME}"
     mv -v "/usr/lib/node_modules/lamassu-server" "/usr/lib/node_modules/${BKP_NAME}" >> ${LOG_FILE} 2>&1
 fi
-
-decho "updating node"
-npm install n -g >> ${LOG_FILE} 2>&1
-n 8 >> ${LOG_FILE} 2>&1
-decho "version installed $(node -v)"
-export NPM_BIN=$(npm -g bin)
 
 decho "Updating lamassu-server to Electric Enlil v7.5.0..."
 npm -g install lamassu/lamassu-server#release-7.5.0 --unsafe-perm >> ${LOG_FILE} 2>&1
