Add ETH pending transaction check for FF (#90)
* fix: add ETH pending transaction check

* fix: lock files

* fix: avoid mkdir error message

* fix: ETH first tx timestamp and null check

* fix: instructions and script url

diff --git a/upgrade-ls b/upgrade-ls
--- a/upgrade-ls
+++ b/upgrade-ls
@@ -44,6 +44,38 @@ if [[ "$UBUNTU_VERSION" == "20.04" ]]; then
 
   export NPM_BIN=$(npm -g bin)
 
+  # Check if ETH was transacted for the first time before 8.0
+  SERVER_RELEASE=$(node -p -e "require('$(npm root -g)/lamassu-server/package.json').version")
+  REQUIRED_RELEASE=8.0.0-beta.5
+
+  if [ $(printf "%s\n" "$SERVER_RELEASE" "$REQUIRED_RELEASE" | sort -V | head -1) = "$SERVER_RELEASE" ]
+  then
+    if [ -d /var/lock/lamassu-eth-pending-sweep-finished ]; then
+      : # no-op, continue the upgrade
+    elif ! mkdir /var/lock/lamassu-eth-pending-sweep; then
+      echo "Upgrading l-s is locked because of an intended halt. Please contact support for more info" >&2
+      rm -r /var/lock/lamassu-update
+      exit 1
+    else
+      CONFIG_DIR=/etc/lamassu
+      CONNECTION_STRING_TEMP=$(grep -oP '(?<="postgresql": ")[^"]*' $CONFIG_DIR/lamassu.json)
+      CONNECTION_STRING=$(echo "${CONNECTION_STRING_TEMP/psql/"postgresql"}")
+
+      FIRST_FF_MIGRATION_TIME=$(psql -d $CONNECTION_STRING -Atc "SELECT value->>'timestamp' FROM migrations m, json_array_elements(m.data->'migrations') obj WHERE obj->>'title' = '1603804834628-add-last-accessed-tokens.js';")
+      FIRST_ETH_TX_TIME=$(psql -d $CONNECTION_STRING -Atc "SELECT EXTRACT(EPOCH FROM created) * 1000 FROM (SELECT id, crypto_code, created FROM cash_in_txs UNION SELECT id, crypto_code, created FROM cash_out_txs) txs WHERE txs.crypto_code = 'ETH' ORDER BY created ASC LIMIT 1;")
+
+      if [ -z "${FIRST_ETH_TX_TIME}" ]; then
+        : # no-op, continue the upgrade
+      elif [ $FIRST_ETH_TX_TIME \> $FIRST_FF_MIGRATION_TIME ]; then
+        echo -e "\n\033[0;31mAn Ethereum transaction was detected to have been made for the first time after the v8.0 beta upgrade.\n\nThis is okay, but will require a unique update path. In order to continue, please contact support for specific update instructions.\n\nMeanwhile, your server and machine(s) continue to run current versions.\033[0m\n"
+        curl -o $(npm root -g)/lamassu-server/bin/lamassu-eth-sweep-to-new-wallet https://raw.githubusercontent.com/lamassu/lamassu-server/release-8.0/bin/lamassu-eth-sweep-to-new-wallet >> ${LOG_FILE} 2>&1
+        rm -r /var/lock/lamassu-update
+        exit 1
+      fi
+      rm -r /var/lock/lamassu-eth-pending-sweep
+    fi
+  fi
+
   decho "stopping lamassu-server"
   supervisorctl stop lamassu-server >> ${LOG_FILE} 2>&1
   supervisorctl stop lamassu-admin-server >> ${LOG_FILE} 2>&1
@@ -147,3 +179,7 @@ fi
 hash -r
 
 rm -r /var/lock/lamassu-update
+
+if [ -d /var/lock/lamassu-eth-pending-sweep-finished ]; then
+  rm -r /var/lock/lamassu-eth-pending-sweep-finished
+fi
