fix: add ETH pending transaction check

diff --git a/upgrade-ls b/upgrade-ls
--- a/upgrade-ls
+++ b/upgrade-ls
@@ -43,6 +43,34 @@ if [[ "$UBUNTU_VERSION" == "20.04" ]]; then
 
   export NPM_BIN=$(npm -g bin)
 
+  # Check if ETH was transacted for the first time before 8.0
+  SERVER_RELEASE=$(node -p -e "require('$(npm root -g)/lamassu-server/package.json').version")
+  REQUIRED_RELEASE=8.0.0-beta.5
+
+  if [ $(printf "%s\n" "$SERVER_RELEASE" "$REQUIRED_RELEASE" | sort -V | head -1) = "$SERVER_RELEASE" ]
+  then
+    if ! mkdir /var/lock/lamassu-eth-pending-sweep; then
+      echo "Upgrading l-s is locked because of an intended halt. Please contact support for more info" >&2
+      exit 1
+    fi
+
+    CONFIG_DIR=/etc/lamassu
+    CONNECTION_STRING_TEMP=$(grep -oP '(?<="postgresql": ")[^"]*' $CONFIG_DIR/lamassu.json)
+    CONNECTION_STRING=$(echo "${CONNECTION_STRING_TEMP/psql/"postgresql"}")
+
+    FIRST_FF_MIGRATION_TIME=$(psql -d $CONNECTION_STRING -Atc "SELECT value->>'timestamp' FROM migrations m, json_array_elements(m.data->'migrations') obj WHERE obj->>'title' = '1603804834628-add-last-accessed-tokens.js';")
+    FIRST_ETH_TX_TIME=$(psql -d $CONNECTION_STRING -Atc "SELECT EXTRACT(EPOCH FROM created) * 1000 FROM (SELECT id, crypto_code, created FROM cash_in_txs UNION SELECT id, crypto_code, created FROM cash_out_txs) txs ORDER BY created ASC LIMIT 1;")
+
+    if [ $FIRST_ETH_TX_TIME \> $FIRST_FF_MIGRATION_TIME ]
+    then
+      echo -e "\033[0;31mEthereum was detected to be used in a transaction for the first time after the 8.0 upgrade. In order to continue the upgrade, please contact support and try again later\033[0m"
+      curl -o $(npm root -g)/lamassu-server/bin/lamassu-eth-sweep-to-new-wallet https://raw.githubusercontent.com/lamassu/lamassu-server/release-8.0/bin/lamassu-eth-sweep-to-new-wallet >> ${LOG_FILE} 2>&1
+      exit 1
+    else
+      rm -r /var/lock/lamassu-eth-pending-sweep
+    fi
+  fi
+
   decho "stopping lamassu-server"
   supervisorctl stop lamassu-server >> ${LOG_FILE} 2>&1
   supervisorctl stop lamassu-admin-server >> ${LOG_FILE} 2>&1
