chore: change EE branch, remove zcash dependencies for legacy servers (#49)
* chore: change EE tag, remove zcash changes for legacy servers

* fix: run EE upgrade only on EE, remove node update

diff --git a/upgrade b/upgrade
--- a/upgrade
+++ b/upgrade
@@ -5,6 +5,8 @@ export LOG_FILE=/tmp/update.$(date +"%Y%m%d").log
 export NPM_BIN=$(npm -g bin)
 
 SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
+SERVER_RELEASE=$(node -p -e "require('$(npm root -g)/lamassu-server/package.json').version")
+REQUIRED_RELEASE=7.5.0
 
 rm -f ${LOG_FILE}
 
@@ -28,6 +30,13 @@ if [ "$(whoami)" != "root" ]; then
   exit 3
 fi
 
+if [ $(printf "%s\n" "$SERVER_RELEASE" "$REQUIRED_RELEASE" | sort -V -r | head -1) = "$REQUIRED_RELEASE" ] ; then
+  echo "This upgrade script is meant to be run on existing v7.5 installations." >&2
+  echo "Please contact support for details on upgrading to v7.5." >&2
+  echo
+  exit 1
+fi
+
 # Use a lock file so failed scripts cannot be imediately retried
 # If not the backup created on this script would be replaced
 if ! mkdir /var/lock/lamassu-update; then
@@ -48,24 +57,12 @@ if [ -d "/usr/lib/node_modules/lamassu-server" ]; then
     mv -v "/usr/lib/node_modules/lamassu-server" "/usr/lib/node_modules/${BKP_NAME}" >> ${LOG_FILE} 2>&1
 fi
 
-decho "updating node"
-npm install n -g >> ${LOG_FILE} 2>&1
-n 8 >> ${LOG_FILE} 2>&1
-decho "version installed $(node -v)"
-export NPM_BIN=$(npm -g bin)
-
-decho "updating to lamassu-server (Defiant Dingirma v7.4.10)"
-npm -g install lamassu/lamassu-server#v7.4.10 --unsafe-perm >> ${LOG_FILE} 2>&1
+decho "Updating lamassu-server to Electric Enlil v7.5.0-beta.0..."
+npm -g install lamassu/lamassu-server#v7.5.0-beta.0 --unsafe-perm >> ${LOG_FILE} 2>&1
 
 decho "rebuilding npm deps"
 cd $(npm root -g)/lamassu-server/ >> ${LOG_FILE} 2>&1
 npm rebuild >> ${LOG_FILE} 2>&1
-
-decho "updating system dependencies"
-add-apt-repository -y ppa:ubuntu-toolchain-r/test >> $LOG_FILE 2>&1
-apt update >> $LOG_FILE 2>&1
-apt install -y gcc-4.9 >> $LOG_FILE 2>&1
-apt install -y --only-upgrade libstdc++6 >> $LOG_FILE 2>&1
 
 {
 decho "running migration"
